export const TASKS_REQUEST = 'TASKS_REQUEST';
export const TASKS_TASK_EXECUTORS_REQUEST = 'TASKS_TASK_EXECUTORS_REQUEST';
export const TASKS_EXECUTOR_EDIT_MODE = 'TASKS_EXECUTOR_EDIT_MODE';
export const TASKS_EXECUTOR_VIEW_MODE = 'TASKS_EXECUTOR_VIEW_MODE';
export const TASKS_EXECUTOR_UPDATE_REQUEST = 'TASKS_EXECUTOR_UPDATE_REQUEST';
